<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BreadIngredientsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks to avoid errors during truncation
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        // Get the next available ID for service_charge
        $lastId = DB::table('service_charge')->max('id') ?? 0;

        DB::table('service_charge')->insert([
            [
                'id' => $lastId + 1,
                'code' => 'BRD-001',
                'name' => 'High Protein Flour',
                'full_name' => 'BRD-001, High Protein Flour [RAW MATERIAL]',
                'type' => null,
                'transport' => null,
                'buying_coa_id' => 56, // Investment In Stocks
                'selling_coa_id' => 56, // Investment In Stocks
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'service_charge_group_id' => 18, // RAW MATERIAL
                'item_type_id' => 4, // Raw Material
            ],
            [
                'id' => $lastId + 2,
                'code' => 'BRD-002',
                'name' => 'Instant Yeast',
                'full_name' => 'BRD-002, Instant Yeast [RAW MATERIAL]',
                'type' => null,
                'transport' => null,
                'buying_coa_id' => 56,
                'selling_coa_id' => 56,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'service_charge_group_id' => 18,
                'item_type_id' => 4,
            ],
            [
                'id' => $lastId + 3,
                'code' => 'BRD-003',
                'name' => 'White Sugar',
                'full_name' => 'BRD-003, White Sugar [RAW MATERIAL]',
                'type' => null,
                'transport' => null,
                'buying_coa_id' => 56,
                'selling_coa_id' => 56,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'service_charge_group_id' => 18,
                'item_type_id' => 4,
            ],
            [
                'id' => $lastId + 4,
                'code' => 'BRD-004',
                'name' => 'Salt',
                'full_name' => 'BRD-004, Salt [RAW MATERIAL]',
                'type' => null,
                'transport' => null,
                'buying_coa_id' => 56,
                'selling_coa_id' => 56,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'service_charge_group_id' => 18,
                'item_type_id' => 4,
            ],
            [
                'id' => $lastId + 5,
                'code' => 'BRD-005',
                'name' => 'Butter',
                'full_name' => 'BRD-005, Butter [RAW MATERIAL]',
                'type' => null,
                'transport' => null,
                'buying_coa_id' => 56,
                'selling_coa_id' => 56,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'service_charge_group_id' => 18,
                'item_type_id' => 4,
            ],
            [
                'id' => $lastId + 6,
                'code' => 'BRD-006',
                'name' => 'Fresh Milk',
                'full_name' => 'BRD-006, Fresh Milk [RAW MATERIAL]',
                'type' => null,
                'transport' => null,
                'buying_coa_id' => 56,
                'selling_coa_id' => 56,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'service_charge_group_id' => 18,
                'item_type_id' => 4,
            ],
            [
                'id' => $lastId + 7,
                'code' => 'BRD-007',
                'name' => 'Chicken Eggs',
                'full_name' => 'BRD-007, Chicken Eggs [RAW MATERIAL]',
                'type' => null,
                'transport' => null,
                'buying_coa_id' => 56,
                'selling_coa_id' => 56,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'service_charge_group_id' => 18,
                'item_type_id' => 4,
            ],
            [
                'id' => $lastId + 8,
                'code' => 'BRD-008',
                'name' => 'Vegetable Oil',
                'full_name' => 'BRD-008, Vegetable Oil [RAW MATERIAL]',
                'type' => null,
                'transport' => null,
                'buying_coa_id' => 56,
                'selling_coa_id' => 56,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'service_charge_group_id' => 18,
                'item_type_id' => 4,
            ],
            [
                'id' => $lastId + 9,
                'code' => 'BRD-009',
                'name' => 'Baking Powder',
                'full_name' => 'BRD-009, Baking Powder [RAW MATERIAL]',
                'type' => null,
                'transport' => null,
                'buying_coa_id' => 56,
                'selling_coa_id' => 56,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'service_charge_group_id' => 18,
                'item_type_id' => 4,
            ],
            [
                'id' => $lastId + 10,
                'code' => 'BRD-010',
                'name' => 'Vanilla Extract',
                'full_name' => 'BRD-010, Vanilla Extract [RAW MATERIAL]',
                'type' => null,
                'transport' => null,
                'buying_coa_id' => 56,
                'selling_coa_id' => 56,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'service_charge_group_id' => 18,
                'item_type_id' => 4,
            ],
            [
                'id' => $lastId + 11,
                'code' => 'BRD-011',
                'name' => 'Whole Wheat Flour',
                'full_name' => 'BRD-011, Whole Wheat Flour [RAW MATERIAL]',
                'type' => null,
                'transport' => null,
                'buying_coa_id' => 56,
                'selling_coa_id' => 56,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'service_charge_group_id' => 18,
                'item_type_id' => 4,
            ],
            [
                'id' => $lastId + 12,
                'code' => 'BRD-012',
                'name' => 'Brown Sugar',
                'full_name' => 'BRD-012, Brown Sugar [RAW MATERIAL]',
                'type' => null,
                'transport' => null,
                'buying_coa_id' => 56,
                'selling_coa_id' => 56,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'service_charge_group_id' => 18,
                'item_type_id' => 4,
            ],
            [
                'id' => $lastId + 13,
                'code' => 'BRD-013',
                'name' => 'Honey',
                'full_name' => 'BRD-013, Honey [RAW MATERIAL]',
                'type' => null,
                'transport' => null,
                'buying_coa_id' => 56,
                'selling_coa_id' => 56,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'service_charge_group_id' => 18,
                'item_type_id' => 4,
            ],
            [
                'id' => $lastId + 14,
                'code' => 'BRD-014',
                'name' => 'Cinnamon Powder',
                'full_name' => 'BRD-014, Cinnamon Powder [RAW MATERIAL]',
                'type' => null,
                'transport' => null,
                'buying_coa_id' => 56,
                'selling_coa_id' => 56,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'service_charge_group_id' => 18,
                'item_type_id' => 4,
            ],
            [
                'id' => $lastId + 15,
                'code' => 'BRD-015',
                'name' => 'Chocolate Chips',
                'full_name' => 'BRD-015, Chocolate Chips [RAW MATERIAL]',
                'type' => null,
                'transport' => null,
                'buying_coa_id' => 56,
                'selling_coa_id' => 56,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'service_charge_group_id' => 18,
                'item_type_id' => 4,
            ],
        ]);

        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
