<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ServiceChargeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks to avoid errors during truncation
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        
        DB::table('service_charge')->truncate();
        
        DB::table('service_charge')->insert([
            [
  'id' => 1,
  'code' => 'ACFC',
  'name' => 'Additonal Charge For Service/Clearance Doc.',
  'full_name' => 'ACFC, Additonal Charge For Service/Clearance Doc. [HDLG]',
  'type' => 'import',
  'transport' => 'air',
  'buying_coa_id' => 182,
  'selling_coa_id' => 114,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 2,
  'code' => 'ACIA',
  'name' => 'Import Air Aci',
  'full_name' => 'ACIA, Import Air Aci [FRGT]',
  'type' => 'import',
  'transport' => 'air',
  'buying_coa_id' => 176,
  'selling_coa_id' => 108,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 3,
  'code' => 'AEUN',
  'name' => 'Air Export Licence Fee',
  'full_name' => 'AEUN, Air Export Licence Fee [HDLG]',
  'type' => 'export',
  'transport' => 'air',
  'buying_coa_id' => 166,
  'selling_coa_id' => 98,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 4,
  'code' => 'AFTE',
  'name' => 'Export Air Freight',
  'full_name' => 'AFTE, Export Air Freight [FRGT]',
  'type' => 'export',
  'transport' => 'air',
  'buying_coa_id' => 178,
  'selling_coa_id' => 110,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 5,
  'code' => 'AIRFF',
  'name' => 'Import Air-Airport Transfer',
  'full_name' => 'AIRFF, Import Air-Airport Transfer [FRGT]',
  'type' => 'import',
  'transport' => 'air',
  'buying_coa_id' => 176,
  'selling_coa_id' => 108,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 6,
  'code' => 'ATFP',
  'name' => 'Import Air Tunnel Fee / Parking',
  'full_name' => 'ATFP, Import Air Tunnel Fee / Parking [FRGT]',
  'type' => 'import',
  'transport' => 'air',
  'buying_coa_id' => 176,
  'selling_coa_id' => 108,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 7,
  'code' => 'AWBI',
  'name' => 'Import Air Awb Fee, Ams',
  'full_name' => 'AWBI, Import Air Awb Fee, Ams [FRGT]',
  'type' => 'import',
  'transport' => 'air',
  'buying_coa_id' => 176,
  'selling_coa_id' => 108,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 8,
  'code' => 'BLES',
  'name' => 'Export Sea B/L',
  'full_name' => 'BLES, Export Sea B/L [CSTM]',
  'type' => 'export',
  'transport' => 'sea',
  'buying_coa_id' => 184,
  'selling_coa_id' => 116,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => 4,
  'item_type_id' => NULL,
],
            [
  'id' => 9,
  'code' => 'BNTA',
  'name' => 'Air Notul',
  'full_name' => 'BNTA, Air Notul [RMBS]',
  'type' => '',
  'transport' => 'air',
  'buying_coa_id' => 31,
  'selling_coa_id' => 31,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 10,
  'code' => 'BNTS',
  'name' => 'Sea Notul',
  'full_name' => 'BNTS, Sea Notul [RMBS]',
  'type' => '',
  'transport' => 'sea',
  'buying_coa_id' => 31,
  'selling_coa_id' => 31,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 11,
  'code' => 'CFID',
  'name' => 'Cfs Fee In Destination',
  'full_name' => 'CFID, Cfs Fee In Destination [HDLG]',
  'type' => '',
  'transport' => '',
  'buying_coa_id' => 162,
  'selling_coa_id' => 94,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 12,
  'code' => 'CFSC',
  'name' => 'Import Sea Cfs',
  'full_name' => 'CFSC, Import Sea Cfs [FRGT]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 177,
  'selling_coa_id' => 109,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 13,
  'code' => 'CSDF',
  'name' => 'Import Air Custom Declaration Fee',
  'full_name' => 'CSDF, Import Air Custom Declaration Fee [FRGT]',
  'type' => 'import',
  'transport' => 'air',
  'buying_coa_id' => 176,
  'selling_coa_id' => 108,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 14,
  'code' => 'CSSF',
  'name' => 'Import Sea Custom Declaration Fee',
  'full_name' => 'CSSF, Import Sea Custom Declaration Fee [FRGT]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 177,
  'selling_coa_id' => 109,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 15,
  'code' => 'DCDD',
  'name' => 'Deposit Container, Demurage, Detention',
  'full_name' => 'DCDD, Deposit Container, Demurage, Detention [RMBS]',
  'type' => '',
  'transport' => '',
  'buying_coa_id' => 38,
  'selling_coa_id' => 38,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 16,
  'code' => 'DCFA',
  'name' => 'Import Air Document Fee',
  'full_name' => 'DCFA, Import Air Document Fee [CSTM]',
  'type' => 'import',
  'transport' => 'air',
  'buying_coa_id' => 181,
  'selling_coa_id' => 113,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => 4,
  'item_type_id' => NULL,
],
            [
  'id' => 17,
  'code' => 'DCFS',
  'name' => 'Import Sea Document Fee Agent',
  'full_name' => 'DCFS, Import Sea Document Fee Agent [FRGT]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 177,
  'selling_coa_id' => 109,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 18,
  'code' => 'DFWF',
  'name' => 'Import Sea Dfw Fob & Custom Charge',
  'full_name' => 'DFWF, Import Sea Dfw Fob & Custom Charge [FRGT]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 177,
  'selling_coa_id' => 109,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 19,
  'code' => 'DGCF',
  'name' => 'Dg Cargo Fee',
  'full_name' => 'DGCF, Dg Cargo Fee [FRGT]',
  'type' => '',
  'transport' => '',
  'buying_coa_id' => 177,
  'selling_coa_id' => 109,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 20,
  'code' => 'DTCS',
  'name' => 'Import Sea Delivery / Transp Charges',
  'full_name' => 'DTCS, Import Sea Delivery / Transp Charges [FRGT]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 177,
  'selling_coa_id' => 109,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 21,
  'code' => 'EAEF',
  'name' => 'Export Air Edi Fee',
  'full_name' => 'EAEF, Export Air Edi Fee [CSTM]',
  'type' => 'export',
  'transport' => 'air',
  'buying_coa_id' => 166,
  'selling_coa_id' => 98,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => 4,
  'item_type_id' => NULL,
],
            [
  'id' => 22,
  'code' => 'EAFI',
  'name' => 'Import Air Freight, Fsc. Scc',
  'full_name' => 'EAFI, Import Air Freight, Fsc. Scc [FRGT]',
  'type' => 'import',
  'transport' => 'air',
  'buying_coa_id' => 176,
  'selling_coa_id' => 108,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 23,
  'code' => 'EAOC',
  'name' => 'Export Air Other Cost',
  'full_name' => 'EAOC, Export Air Other Cost [OTRC]',
  'type' => 'export',
  'transport' => 'air',
  'buying_coa_id' => 215,
  'selling_coa_id' => 148,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 24,
  'code' => 'EAVI',
  'name' => 'Export Air Vat In',
  'full_name' => 'EAVI, Export Air Vat In [IDTX]',
  'type' => 'export',
  'transport' => 'air',
  'buying_coa_id' => 35,
  'selling_coa_id' => 35,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 25,
  'code' => 'EAWA',
  'name' => 'Export Air Awb',
  'full_name' => 'EAWA, Export Air Awb [FRGT]',
  'type' => 'export',
  'transport' => 'air',
  'buying_coa_id' => 178,
  'selling_coa_id' => 110,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 26,
  'code' => 'EDFA',
  'name' => 'Import Air Edi Fee',
  'full_name' => 'EDFA, Import Air Edi Fee [CSTM]',
  'type' => 'import',
  'transport' => 'air',
  'buying_coa_id' => 207,
  'selling_coa_id' => 139,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => 4,
  'item_type_id' => NULL,
],
            [
  'id' => 27,
  'code' => 'EDFS',
  'name' => 'Import Sea Edi Fee',
  'full_name' => 'EDFS, Import Sea Edi Fee [CSTM]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 208,
  'selling_coa_id' => 140,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => 4,
  'item_type_id' => NULL,
],
            [
  'id' => 28,
  'code' => 'EIFA',
  'name' => 'Import Air Edi Fee Agent',
  'full_name' => 'EIFA, Import Air Edi Fee Agent [FRGT]',
  'type' => 'import',
  'transport' => 'air',
  'buying_coa_id' => 176,
  'selling_coa_id' => 108,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 29,
  'code' => 'ESFE',
  'name' => 'Export Sea Freight',
  'full_name' => 'ESFE, Export Sea Freight [FRGT]',
  'type' => 'export',
  'transport' => 'sea',
  'buying_coa_id' => 179,
  'selling_coa_id' => 111,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 30,
  'code' => 'ESFI',
  'name' => 'Import Sea Freight Lcl',
  'full_name' => 'ESFI, Import Sea Freight Lcl [FRGT]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 177,
  'selling_coa_id' => 109,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 31,
  'code' => 'ESOC',
  'name' => 'Export  Sea Other Cost',
  'full_name' => 'ESOC, Export  Sea Other Cost [OTRC]',
  'type' => 'export',
  'transport' => 'sea',
  'buying_coa_id' => 215,
  'selling_coa_id' => 149,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 32,
  'code' => 'ESVI',
  'name' => 'Export Sea Vat In',
  'full_name' => 'ESVI, Export Sea Vat In [IDTX]',
  'type' => 'export',
  'transport' => 'sea',
  'buying_coa_id' => 35,
  'selling_coa_id' => 35,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 33,
  'code' => 'ETRA',
  'name' => 'Export Air Trucking',
  'full_name' => 'ETRA, Export Air Trucking [TRCK]',
  'type' => 'export',
  'transport' => 'air',
  'buying_coa_id' => 194,
  'selling_coa_id' => 126,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 34,
  'code' => 'ETS5',
  'name' => 'Export Sea Trucking Fcl 45',
  'full_name' => 'ETS5, Export Sea Trucking Fcl 45 [TRCK]',
  'type' => 'export',
  'transport' => 'sea',
  'buying_coa_id' => 198,
  'selling_coa_id' => 130,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 35,
  'code' => 'ETSF',
  'name' => 'Export Sea Trucking Fcl 40',
  'full_name' => 'ETSF, Export Sea Trucking Fcl 40 [TRCK]',
  'type' => 'export',
  'transport' => 'sea',
  'buying_coa_id' => 197,
  'selling_coa_id' => 129,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 36,
  'code' => 'ETSL',
  'name' => 'Export Sea Trucking Lcl',
  'full_name' => 'ETSL, Export Sea Trucking Lcl [TRCK]',
  'type' => 'export',
  'transport' => 'sea',
  'buying_coa_id' => 199,
  'selling_coa_id' => 131,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 37,
  'code' => 'ETST',
  'name' => 'Export Sea Trucking Fcl 20',
  'full_name' => 'ETST, Export Sea Trucking Fcl 20 [TRCK]',
  'type' => 'export',
  'transport' => 'sea',
  'buying_coa_id' => 196,
  'selling_coa_id' => 128,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 38,
  'code' => 'EWHS',
  'name' => 'Air Export Warehouse',
  'full_name' => 'EWHS, Air Export Warehouse [WRHS]',
  'type' => 'export',
  'transport' => 'air',
  'buying_coa_id' => 166,
  'selling_coa_id' => 98,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 39,
  'code' => 'EXPH',
  'name' => 'Export Air Handling Agent',
  'full_name' => 'EXPH, Export Air Handling Agent [FRGT]',
  'type' => 'export',
  'transport' => 'air',
  'buying_coa_id' => 178,
  'selling_coa_id' => 110,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 40,
  'code' => 'FMHS',
  'name' => 'Import Sea Fumigation',
  'full_name' => 'FMHS, Import Sea Fumigation [FRGT]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 177,
  'selling_coa_id' => 109,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 41,
  'code' => 'FRAD',
  'name' => 'Import Sea Form E Additional Pages Fee',
  'full_name' => 'FRAD, Import Sea Form E Additional Pages Fee [FRGT]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 177,
  'selling_coa_id' => 109,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 42,
  'code' => 'FRAF',
  'name' => 'Freight Amendment Fee',
  'full_name' => 'FRAF, Freight Amendment Fee [FRGT]',
  'type' => '',
  'transport' => '',
  'buying_coa_id' => 177,
  'selling_coa_id' => 109,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 43,
  'code' => 'FREW',
  'name' => 'Import Sea Exwork Charges',
  'full_name' => 'FREW, Import Sea Exwork Charges [FRGT]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 177,
  'selling_coa_id' => 109,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 44,
  'code' => 'FRME',
  'name' => 'Import Sea Form E Apply Fee',
  'full_name' => 'FRME, Import Sea Form E Apply Fee [FRGT]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 177,
  'selling_coa_id' => 109,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 45,
  'code' => 'FWBF',
  'name' => 'Import Air Fwb Transmission Fee',
  'full_name' => 'FWBF, Import Air Fwb Transmission Fee [FRGT]',
  'type' => 'import',
  'transport' => 'air',
  'buying_coa_id' => 176,
  'selling_coa_id' => 108,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 46,
  'code' => 'GCIM',
  'name' => 'Import Air Gate Charges',
  'full_name' => 'GCIM, Import Air Gate Charges [FRGT]',
  'type' => 'import',
  'transport' => 'air',
  'buying_coa_id' => 176,
  'selling_coa_id' => 108,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 47,
  'code' => 'GNRI',
  'name' => 'Sea Gri',
  'full_name' => 'GNRI, Sea Gri [FRGT]',
  'type' => '',
  'transport' => 'sea',
  'buying_coa_id' => 177,
  'selling_coa_id' => 109,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 48,
  'code' => 'HDIA',
  'name' => 'Import Air Handling',
  'full_name' => 'HDIA, Import Air Handling [HDLG]',
  'type' => 'import',
  'transport' => 'air',
  'buying_coa_id' => 156,
  'selling_coa_id' => 88,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 49,
  'code' => 'HDSA',
  'name' => 'Import Air Handling Agent',
  'full_name' => 'HDSA, Import Air Handling Agent [FRGT]',
  'type' => 'import',
  'transport' => 'air',
  'buying_coa_id' => 176,
  'selling_coa_id' => 108,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 50,
  'code' => 'HDSE',
  'name' => 'Import Sea Handling Agent',
  'full_name' => 'HDSE, Import Sea Handling Agent [FRGT]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 177,
  'selling_coa_id' => 109,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 51,
  'code' => 'HEXA',
  'name' => 'Export Air Handling',
  'full_name' => 'HEXA, Export Air Handling [HDLG]',
  'type' => 'export',
  'transport' => 'air',
  'buying_coa_id' => 166,
  'selling_coa_id' => 98,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 52,
  'code' => 'HEXF',
  'name' => 'Export Sea Handling Fcl 40',
  'full_name' => 'HEXF, Export Sea Handling Fcl 40 [HDLG]',
  'type' => 'export',
  'transport' => 'sea',
  'buying_coa_id' => 170,
  'selling_coa_id' => 102,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 53,
  'code' => 'HEXL',
  'name' => 'Export Sea Handling Lcl',
  'full_name' => 'HEXL, Export Sea Handling Lcl [HDLG]',
  'type' => 'export',
  'transport' => 'sea',
  'buying_coa_id' => 173,
  'selling_coa_id' => 105,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 54,
  'code' => 'HEXS',
  'name' => 'Export Sea Handling Fcl 45',
  'full_name' => 'HEXS, Export Sea Handling Fcl 45 [HDLG]',
  'type' => 'export',
  'transport' => 'sea',
  'buying_coa_id' => 171,
  'selling_coa_id' => 103,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 55,
  'code' => 'HEXT',
  'name' => 'Export Sea Handling Fcl 20',
  'full_name' => 'HEXT, Export Sea Handling Fcl 20 [HDLG]',
  'type' => 'export',
  'transport' => 'sea',
  'buying_coa_id' => 169,
  'selling_coa_id' => 101,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 56,
  'code' => 'HIEA',
  'name' => 'Export Air Handling All In',
  'full_name' => 'HIEA, Export Air Handling All In [HDLG]',
  'type' => 'export',
  'transport' => 'air',
  'buying_coa_id' => 168,
  'selling_coa_id' => 100,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 57,
  'code' => 'HIES',
  'name' => 'Export Sea Handling All In',
  'full_name' => 'HIES, Export Sea Handling All In [HDLG]',
  'type' => 'export',
  'transport' => 'sea',
  'buying_coa_id' => 174,
  'selling_coa_id' => 106,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 58,
  'code' => 'HILC',
  'name' => 'Import Sea Handling Lcl',
  'full_name' => 'HILC, Import Sea Handling Lcl [HDLG]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 162,
  'selling_coa_id' => 94,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 59,
  'code' => 'HISF',
  'name' => 'Import Sea Handling Fcl 20',
  'full_name' => 'HISF, Import Sea Handling Fcl 20 [HDLG]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 159,
  'selling_coa_id' => 91,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 60,
  'code' => 'HISL',
  'name' => 'Import Sea Handling Fcl 40',
  'full_name' => 'HISL, Import Sea Handling Fcl 40 [HDLG]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 160,
  'selling_coa_id' => 92,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 61,
  'code' => 'HIST',
  'name' => 'Import Sea Handling Fcl 45',
  'full_name' => 'HIST, Import Sea Handling Fcl 45 [HDLG]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 161,
  'selling_coa_id' => 93,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:53',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 62,
  'code' => 'IACH',
  'name' => 'Import Air Terminal Fee, Cross Harbour',
  'full_name' => 'IACH, Import Air Terminal Fee, Cross Harbour [FRGT]',
  'type' => 'import',
  'transport' => 'air',
  'buying_coa_id' => 176,
  'selling_coa_id' => 108,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 63,
  'code' => 'IADT',
  'name' => 'Import Air Duty Tax',
  'full_name' => 'IADT, Import Air Duty Tax [SPCR]',
  'type' => 'import',
  'transport' => 'air',
  'buying_coa_id' => 272,
  'selling_coa_id' => 272,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 64,
  'code' => 'IAHH',
  'name' => 'Import Air Hp Handling',
  'full_name' => 'IAHH, Import Air Hp Handling [HDLG]',
  'type' => 'import',
  'transport' => 'air',
  'buying_coa_id' => 158,
  'selling_coa_id' => 90,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 65,
  'code' => 'IAOC',
  'name' => 'Import Air Other Cost',
  'full_name' => 'IAOC, Import Air Other Cost [FRGT]',
  'type' => 'import',
  'transport' => 'air',
  'buying_coa_id' => 215,
  'selling_coa_id' => 146,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 66,
  'code' => 'IAPF',
  'name' => 'Import Air Permit, Registration Fee',
  'full_name' => 'IAPF, Import Air Permit, Registration Fee [FRGT]',
  'type' => 'import',
  'transport' => 'air',
  'buying_coa_id' => 176,
  'selling_coa_id' => 108,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 67,
  'code' => 'IAPS',
  'name' => 'Import Ait Peak Season Surcharge',
  'full_name' => 'IAPS, Import Ait Peak Season Surcharge [FRGT]',
  'type' => 'import',
  'transport' => 'air',
  'buying_coa_id' => 176,
  'selling_coa_id' => 108,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 68,
  'code' => 'IASF',
  'name' => 'Import Air Stamp Fee',
  'full_name' => 'IASF, Import Air Stamp Fee [FRGT]',
  'type' => 'import',
  'transport' => 'air',
  'buying_coa_id' => 176,
  'selling_coa_id' => 108,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 69,
  'code' => 'IATC',
  'name' => 'Import Air Trucking Local Cdd',
  'full_name' => 'IATC, Import Air Trucking Local Cdd [TRCK]',
  'type' => 'import',
  'transport' => 'air',
  'buying_coa_id' => 186,
  'selling_coa_id' => 118,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 70,
  'code' => 'IATF',
  'name' => 'Import Air Trucking Local Fuso',
  'full_name' => 'IATF, Import Air Trucking Local Fuso [TRCK]',
  'type' => 'import',
  'transport' => 'air',
  'buying_coa_id' => 186,
  'selling_coa_id' => 118,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 71,
  'code' => 'IATW',
  'name' => 'Import Air Trucking Local Wingbox',
  'full_name' => 'IATW, Import Air Trucking Local Wingbox [TRCK]',
  'type' => 'import',
  'transport' => 'air',
  'buying_coa_id' => 186,
  'selling_coa_id' => 118,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 72,
  'code' => 'IAVI',
  'name' => 'Import Air Vat In',
  'full_name' => 'IAVI, Import Air Vat In [IDTX]',
  'type' => 'import',
  'transport' => 'air',
  'buying_coa_id' => 35,
  'selling_coa_id' => 35,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 73,
  'code' => 'IAWF',
  'name' => 'Import Air Weighing Fee',
  'full_name' => 'IAWF, Import Air Weighing Fee [FRGT]',
  'type' => 'import',
  'transport' => 'air',
  'buying_coa_id' => 176,
  'selling_coa_id' => 108,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 74,
  'code' => 'IDDB',
  'name' => 'Reimbursement (Dn]',
  'full_name' => 'IDDB, Reimbursement (Dn] [RMBS]',
  'type' => '',
  'transport' => '',
  'buying_coa_id' => 31,
  'selling_coa_id' => 31,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 75,
  'code' => 'IDFH',
  'name' => 'Handling Fee (Cc]',
  'full_name' => 'IDFH, Handling Fee (Cc] [HDLG]',
  'type' => '',
  'transport' => '',
  'buying_coa_id' => 155,
  'selling_coa_id' => 87,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 76,
  'code' => 'IDST',
  'name' => 'Storage Charge (Rc]',
  'full_name' => 'IDST, Storage Charge (Rc] [WRHS]',
  'type' => '',
  'transport' => '',
  'buying_coa_id' => 150,
  'selling_coa_id' => 82,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 77,
  'code' => 'IDTE',
  'name' => 'Transfer Edi (Te]',
  'full_name' => 'IDTE, Transfer Edi (Te] [CSTM]',
  'type' => '',
  'transport' => '',
  'buying_coa_id' => 206,
  'selling_coa_id' => 138,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => 4,
  'item_type_id' => NULL,
],
            [
  'id' => 78,
  'code' => 'IMED',
  'name' => 'Export Air Doc Fee',
  'full_name' => 'IMED, Export Air Doc Fee [CSTM]',
  'type' => 'export',
  'transport' => 'air',
  'buying_coa_id' => 183,
  'selling_coa_id' => 115,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => 4,
  'item_type_id' => NULL,
],
            [
  'id' => 79,
  'code' => 'IMSC',
  'name' => 'Import Air Screening, Xray',
  'full_name' => 'IMSC, Import Air Screening, Xray [FRGT]',
  'type' => 'import',
  'transport' => 'air',
  'buying_coa_id' => 176,
  'selling_coa_id' => 108,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 80,
  'code' => 'IMTA',
  'name' => 'Import Air Trucking',
  'full_name' => 'IMTA, Import Air Trucking [TRCK]',
  'type' => 'import',
  'transport' => 'air',
  'buying_coa_id' => 186,
  'selling_coa_id' => 118,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 81,
  'code' => 'IMTS',
  'name' => 'Import Sea Trucking Lcl',
  'full_name' => 'IMTS, Import Sea Trucking Lcl [TRCK]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 191,
  'selling_coa_id' => 123,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 82,
  'code' => 'INEA',
  'name' => 'Export Air Insurance',
  'full_name' => 'INEA, Export Air Insurance [INSR]',
  'type' => 'export',
  'transport' => 'air',
  'buying_coa_id' => 212,
  'selling_coa_id' => 144,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 83,
  'code' => 'INES',
  'name' => 'Export Sea Insurance',
  'full_name' => 'INES, Export Sea Insurance [INSR]',
  'type' => 'export',
  'transport' => 'sea',
  'buying_coa_id' => 213,
  'selling_coa_id' => 145,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 84,
  'code' => 'INSA',
  'name' => 'Import Air Insurance',
  'full_name' => 'INSA, Import Air Insurance [INSR]',
  'type' => 'import',
  'transport' => 'air',
  'buying_coa_id' => 210,
  'selling_coa_id' => 142,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 85,
  'code' => 'INSS',
  'name' => 'Import Sea Insurance',
  'full_name' => 'INSS, Import Sea Insurance [INSR]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 211,
  'selling_coa_id' => 143,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 86,
  'code' => 'IRLF',
  'name' => 'Import Sea Reloading Fee',
  'full_name' => 'IRLF, Import Sea Reloading Fee [FRGT]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 177,
  'selling_coa_id' => 109,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 87,
  'code' => 'ISBL',
  'name' => 'Import Sea B/L',
  'full_name' => 'ISBL, Import Sea B/L [FRGT]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 177,
  'selling_coa_id' => 109,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 88,
  'code' => 'ISCC',
  'name' => 'Import Sea Custom Clearance',
  'full_name' => 'ISCC, Import Sea Custom Clearance [FRGT]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 177,
  'selling_coa_id' => 109,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 89,
  'code' => 'ISCR',
  'name' => 'Import Sea Unloading Wh Cdd Reefer',
  'full_name' => 'ISCR, Import Sea Unloading Wh Cdd Reefer [TRCK]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 163,
  'selling_coa_id' => 95,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 90,
  'code' => 'ISCT',
  'name' => 'Import Sea Ctg (Export Charge]',
  'full_name' => 'ISCT, Import Sea Ctg (Export Charge] [FRGT]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 177,
  'selling_coa_id' => 109,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 91,
  'code' => 'ISDT',
  'name' => 'Import Sea Duty Tax',
  'full_name' => 'ISDT, Import Sea Duty Tax [RMBS]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 272,
  'selling_coa_id' => 272,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 92,
  'code' => 'ISEA',
  'name' => 'Import Sea Edi Fee Agent',
  'full_name' => 'ISEA, Import Sea Edi Fee Agent [FRGT]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 177,
  'selling_coa_id' => 109,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 93,
  'code' => 'ISFR',
  'name' => 'Import Sea Unloading Wh Fuso Reefer',
  'full_name' => 'ISFR, Import Sea Unloading Wh Fuso Reefer [TRCK]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 163,
  'selling_coa_id' => 95,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 94,
  'code' => 'ISHH',
  'name' => 'Import Sea Hp Handling',
  'full_name' => 'ISHH, Import Sea Hp Handling [HDLG]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 165,
  'selling_coa_id' => 97,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 95,
  'code' => 'ISLT',
  'name' => 'Import Sea Local Trucking By Agent',
  'full_name' => 'ISLT, Import Sea Local Trucking By Agent [FRGT]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 177,
  'selling_coa_id' => 109,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 96,
  'code' => 'ISOC',
  'name' => 'Import Sea Other Cost',
  'full_name' => 'ISOC, Import Sea Other Cost [FRGT]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 215,
  'selling_coa_id' => 147,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 97,
  'code' => 'ISPS',
  'name' => 'Import Sea Peak Season Surcharge',
  'full_name' => 'ISPS, Import Sea Peak Season Surcharge [FRGT]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 177,
  'selling_coa_id' => 109,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 98,
  'code' => 'ISRR',
  'name' => 'Import Sea Trucking Cdd Reefer',
  'full_name' => 'ISRR, Import Sea Trucking Cdd Reefer [TRCK]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 192,
  'selling_coa_id' => 124,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 99,
  'code' => 'ISSF',
  'name' => 'Import Sea Seal Fee',
  'full_name' => 'ISSF, Import Sea Seal Fee [FRGT]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 177,
  'selling_coa_id' => 109,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 100,
  'code' => 'ISTC',
  'name' => 'Import Sea Trucking Cdd',
  'full_name' => 'ISTC, Import Sea Trucking Cdd [TRCK]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 192,
  'selling_coa_id' => 124,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 101,
  'code' => 'ISTF',
  'name' => 'Import Sea Trucking Fuso',
  'full_name' => 'ISTF, Import Sea Trucking Fuso [TRCK]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 192,
  'selling_coa_id' => 124,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 102,
  'code' => 'ISTR',
  'name' => 'Import Sea Trucking Fuso Reefer',
  'full_name' => 'ISTR, Import Sea Trucking Fuso Reefer [TRCK]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 192,
  'selling_coa_id' => 124,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 103,
  'code' => 'ISUC',
  'name' => 'Import Sea Unloading Wh Mk Cdd',
  'full_name' => 'ISUC, Import Sea Unloading Wh Mk Cdd [TRCK]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 163,
  'selling_coa_id' => 95,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 104,
  'code' => 'ISUF',
  'name' => 'Import Sea Unloading Wh Fuso',
  'full_name' => 'ISUF, Import Sea Unloading Wh Fuso [TRCK]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 163,
  'selling_coa_id' => 95,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 105,
  'code' => 'ISVI',
  'name' => 'Import Sea Vat In',
  'full_name' => 'ISVI, Import Sea Vat In [IDTX]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 35,
  'selling_coa_id' => 35,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 106,
  'code' => 'KWIA',
  'name' => 'Import Air Escort',
  'full_name' => 'KWIA, Import Air Escort [HDLG]',
  'type' => 'import',
  'transport' => 'air',
  'buying_coa_id' => 187,
  'selling_coa_id' => 119,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 107,
  'code' => 'KWIS',
  'name' => 'Import Sea Escort',
  'full_name' => 'KWIS, Import Sea Escort [HDLG]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 193,
  'selling_coa_id' => 125,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 108,
  'code' => 'LCCA',
  'name' => 'Import Air Origin Local Charge',
  'full_name' => 'LCCA, Import Air Origin Local Charge [FRGT]',
  'type' => 'import',
  'transport' => 'air',
  'buying_coa_id' => 176,
  'selling_coa_id' => 108,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 109,
  'code' => 'LCCS',
  'name' => 'Import Sea Origin Local Charge',
  'full_name' => 'LCCS, Import Sea Origin Local Charge [FRGT]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 177,
  'selling_coa_id' => 109,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 110,
  'code' => 'LCLE',
  'name' => 'Import Sea Freight Lcl Exwork',
  'full_name' => 'LCLE, Import Sea Freight Lcl Exwork [FRGT]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 177,
  'selling_coa_id' => 109,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 111,
  'code' => 'LDEA',
  'name' => 'Export Air Destination Local Charge',
  'full_name' => 'LDEA, Export Air Destination Local Charge [FRGT]',
  'type' => 'export',
  'transport' => 'air',
  'buying_coa_id' => 178,
  'selling_coa_id' => 110,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 112,
  'code' => 'LDES',
  'name' => 'Export Sea Destination Local Charge',
  'full_name' => 'LDES, Export Sea Destination Local Charge [FRGT]',
  'type' => 'export',
  'transport' => 'sea',
  'buying_coa_id' => 179,
  'selling_coa_id' => 111,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 113,
  'code' => 'LDUL',
  'name' => 'Loading Unloading Logistic',
  'full_name' => 'LDUL, Loading Unloading Logistic [WRHS]',
  'type' => '',
  'transport' => '',
  'buying_coa_id' => 205,
  'selling_coa_id' => 137,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 114,
  'code' => 'LSCA',
  'name' => 'Import Sea Logistic Charge Agent',
  'full_name' => 'LSCA, Import Sea Logistic Charge Agent [FRGT]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 177,
  'selling_coa_id' => 109,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 115,
  'code' => 'LSSS',
  'name' => 'Import Sea Lss',
  'full_name' => 'LSSS, Import Sea Lss [FRGT]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 177,
  'selling_coa_id' => 109,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 116,
  'code' => 'MFID',
  'name' => 'Mechanics Fee In Destination',
  'full_name' => 'MFID, Mechanics Fee In Destination [HDLG]',
  'type' => '',
  'transport' => '',
  'buying_coa_id' => 191,
  'selling_coa_id' => 94,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 117,
  'code' => 'OBCL',
  'name' => 'Import Sea Unloading Wh Lcl',
  'full_name' => 'OBCL, Import Sea Unloading Wh Lcl [HDLG]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 162,
  'selling_coa_id' => 94,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 118,
  'code' => 'OBKF',
  'name' => 'Import Sea Unloading Wh 20',
  'full_name' => 'OBKF, Import Sea Unloading Wh 20 [HDLG]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 159,
  'selling_coa_id' => 91,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 119,
  'code' => 'OBKL',
  'name' => 'Import Sea Unloading Wh 40',
  'full_name' => 'OBKL, Import Sea Unloading Wh 40 [HDLG]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 160,
  'selling_coa_id' => 92,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 120,
  'code' => 'OBKT',
  'name' => 'Import Sea Unloading Wh 45',
  'full_name' => 'OBKT, Import Sea Unloading Wh 45 [HDLG]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 161,
  'selling_coa_id' => 93,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 121,
  'code' => 'OFID',
  'name' => 'Others Fee In Destination',
  'full_name' => 'OFID, Others Fee In Destination [HDLG]',
  'type' => '',
  'transport' => '',
  'buying_coa_id' => 162,
  'selling_coa_id' => 94,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 122,
  'code' => 'OTHR',
  'name' => 'Import Sea Other Charges (Agent]',
  'full_name' => 'OTHR, Import Sea Other Charges (Agent] [FRGT]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 177,
  'selling_coa_id' => 109,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 123,
  'code' => 'OTIM',
  'name' => 'Import Air Other Charges By Agent',
  'full_name' => 'OTIM, Import Air Other Charges By Agent [FRGT]',
  'type' => 'import',
  'transport' => 'air',
  'buying_coa_id' => 176,
  'selling_coa_id' => 108,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 124,
  'code' => 'PCFA',
  'name' => 'Import Air Packing Fee',
  'full_name' => 'PCFA, Import Air Packing Fee [FRGT]',
  'type' => 'import',
  'transport' => 'air',
  'buying_coa_id' => 176,
  'selling_coa_id' => 108,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 125,
  'code' => 'PCFS',
  'name' => 'Import Sea Packing Fee',
  'full_name' => 'PCFS, Import Sea Packing Fee [FRGT]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 177,
  'selling_coa_id' => 109,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 126,
  'code' => 'PEEA',
  'name' => 'Export Air Pe & Peb',
  'full_name' => 'PEEA, Export Air Pe & Peb [CSTM]',
  'type' => 'export',
  'transport' => 'air',
  'buying_coa_id' => 207,
  'selling_coa_id' => 139,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => 4,
  'item_type_id' => NULL,
],
            [
  'id' => 127,
  'code' => 'PEES',
  'name' => 'Export Sea Pe & Peb',
  'full_name' => 'PEES, Export Sea Pe & Peb [CSTM]',
  'type' => 'export',
  'transport' => 'sea',
  'buying_coa_id' => 208,
  'selling_coa_id' => 140,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => 4,
  'item_type_id' => NULL,
],
            [
  'id' => 128,
  'code' => 'PPHP',
  'name' => 'Pph 23 Payable',
  'full_name' => 'PPHP, Pph 23 Payable [IDTX]',
  'type' => '',
  'transport' => '',
  'buying_coa_id' => 63,
  'selling_coa_id' => 63,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 129,
  'code' => 'PTCR',
  'name' => 'Postage & Courier',
  'full_name' => 'PTCR, Postage & Courier [OTRC]',
  'type' => '',
  'transport' => '',
  'buying_coa_id' => 251,
  'selling_coa_id' => 251,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 130,
  'code' => 'PUCA',
  'name' => 'Import Air Pick Up Charge',
  'full_name' => 'PUCA, Import Air Pick Up Charge [FRGT]',
  'type' => 'import',
  'transport' => 'air',
  'buying_coa_id' => 176,
  'selling_coa_id' => 108,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 131,
  'code' => 'PUCS',
  'name' => 'Import Sea Pick Up Charge',
  'full_name' => 'PUCS, Import Sea Pick Up Charge [FRGT]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 177,
  'selling_coa_id' => 109,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 132,
  'code' => 'RADO',
  'name' => 'Air D/O Reimb',
  'full_name' => 'RADO, Air D/O Reimb [RMBS]',
  'type' => '',
  'transport' => 'air',
  'buying_coa_id' => 31,
  'selling_coa_id' => 31,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 133,
  'code' => 'RAFR',
  'name' => 'Air Freight Reimb',
  'full_name' => 'RAFR, Air Freight Reimb [RMBS]',
  'type' => '',
  'transport' => 'air',
  'buying_coa_id' => 31,
  'selling_coa_id' => 31,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 134,
  'code' => 'RAHC',
  'name' => 'Air Handling Charge Reimb',
  'full_name' => 'RAHC, Air Handling Charge Reimb [RMBS]',
  'type' => '',
  'transport' => 'air',
  'buying_coa_id' => 31,
  'selling_coa_id' => 31,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 135,
  'code' => 'RAIR',
  'name' => 'Air Insurance Reimb',
  'full_name' => 'RAIR, Air Insurance Reimb [RMBS]',
  'type' => '',
  'transport' => 'air',
  'buying_coa_id' => 31,
  'selling_coa_id' => 31,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 136,
  'code' => 'RASB',
  'name' => 'Sea Insurance Reimb',
  'full_name' => 'RASB, Sea Insurance Reimb [RMBS]',
  'type' => '',
  'transport' => 'sea',
  'buying_coa_id' => 31,
  'selling_coa_id' => 31,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 137,
  'code' => 'RASR',
  'name' => 'Air Storage Reimb',
  'full_name' => 'RASR, Air Storage Reimb [RMBS]',
  'type' => '',
  'transport' => 'air',
  'buying_coa_id' => 31,
  'selling_coa_id' => 31,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 138,
  'code' => 'RBAH',
  'name' => 'Sea Bahandle Reimb',
  'full_name' => 'RBAH, Sea Bahandle Reimb [RMBS]',
  'type' => '',
  'transport' => 'sea',
  'buying_coa_id' => 31,
  'selling_coa_id' => 31,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 139,
  'code' => 'RBLO',
  'name' => 'Sea Liff Off Reimb',
  'full_name' => 'RBLO, Sea Liff Off Reimb [RMBS]',
  'type' => '',
  'transport' => 'sea',
  'buying_coa_id' => 31,
  'selling_coa_id' => 31,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 140,
  'code' => 'RCCB',
  'name' => 'Air Ccb Ground Handling',
  'full_name' => 'RCCB, Air Ccb Ground Handling [RMBS]',
  'type' => '',
  'transport' => 'air',
  'buying_coa_id' => 31,
  'selling_coa_id' => 31,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 141,
  'code' => 'RCFS',
  'name' => 'Sea Cfs - D/O Lcl Reimb',
  'full_name' => 'RCFS, Sea Cfs - D/O Lcl Reimb [RMBS]',
  'type' => '',
  'transport' => 'sea',
  'buying_coa_id' => 31,
  'selling_coa_id' => 31,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 142,
  'code' => 'RDEA',
  'name' => 'Sea Detention Admin Reimb',
  'full_name' => 'RDEA, Sea Detention Admin Reimb [RMBS]',
  'type' => '',
  'transport' => 'sea',
  'buying_coa_id' => 31,
  'selling_coa_id' => 31,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 143,
  'code' => 'RDEC',
  'name' => 'Sea Det (Combined] Reimb',
  'full_name' => 'RDEC, Sea Det (Combined] Reimb [RMBS]',
  'type' => '',
  'transport' => 'sea',
  'buying_coa_id' => 31,
  'selling_coa_id' => 31,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 144,
  'code' => 'RDEM',
  'name' => 'Sea Demurage Reimb',
  'full_name' => 'RDEM, Sea Demurage Reimb [RMBS]',
  'type' => '',
  'transport' => 'sea',
  'buying_coa_id' => 31,
  'selling_coa_id' => 31,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 145,
  'code' => 'RDET',
  'name' => 'Sea Detention Reimb',
  'full_name' => 'RDET, Sea Detention Reimb [RMBS]',
  'type' => '',
  'transport' => 'sea',
  'buying_coa_id' => 31,
  'selling_coa_id' => 31,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 146,
  'code' => 'RDOA',
  'name' => 'Sea D/O Admin Reimb',
  'full_name' => 'RDOA, Sea D/O Admin Reimb [RMBS]',
  'type' => '',
  'transport' => 'sea',
  'buying_coa_id' => 31,
  'selling_coa_id' => 31,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 147,
  'code' => 'RDOB',
  'name' => 'Sea D/O Reimb',
  'full_name' => 'RDOB, Sea D/O Reimb [RMBS]',
  'type' => '',
  'transport' => 'sea',
  'buying_coa_id' => 31,
  'selling_coa_id' => 31,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 148,
  'code' => 'RDOE',
  'name' => 'Sea D/O Extension Reimb',
  'full_name' => 'RDOE, Sea D/O Extension Reimb [RMBS]',
  'type' => '',
  'transport' => 'sea',
  'buying_coa_id' => 31,
  'selling_coa_id' => 31,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 149,
  'code' => 'REXT',
  'name' => 'Sea Extra Handling Reimb',
  'full_name' => 'REXT, Sea Extra Handling Reimb [RMBS]',
  'type' => '',
  'transport' => 'sea',
  'buying_coa_id' => 31,
  'selling_coa_id' => 31,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 150,
  'code' => 'RFND',
  'name' => 'Export Sea Refund',
  'full_name' => 'RFND, Export Sea Refund [FRGT]',
  'type' => 'export',
  'transport' => 'sea',
  'buying_coa_id' => 179,
  'selling_coa_id' => 111,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 151,
  'code' => 'RHAC',
  'name' => 'Sea Handling Charges Reimb',
  'full_name' => 'RHAC, Sea Handling Charges Reimb [RMBS]',
  'type' => '',
  'transport' => 'sea',
  'buying_coa_id' => 31,
  'selling_coa_id' => 31,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 152,
  'code' => 'RKWR',
  'name' => 'Kawalan Reimb',
  'full_name' => 'RKWR, Kawalan Reimb [RMBS]',
  'type' => '',
  'transport' => '',
  'buying_coa_id' => 31,
  'selling_coa_id' => 31,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 153,
  'code' => 'RMEA',
  'name' => 'Export Air Reimbursement',
  'full_name' => 'RMEA, Export Air Reimbursement [RMBS]',
  'type' => 'export',
  'transport' => 'air',
  'buying_coa_id' => 31,
  'selling_coa_id' => 31,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 154,
  'code' => 'RMEK',
  'name' => 'Sea Mechanic Reimb',
  'full_name' => 'RMEK, Sea Mechanic Reimb [RMBS]',
  'type' => '',
  'transport' => 'sea',
  'buying_coa_id' => 31,
  'selling_coa_id' => 31,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 155,
  'code' => 'RMES',
  'name' => 'Export Sea Reimbursement',
  'full_name' => 'RMES, Export Sea Reimbursement [RMBS]',
  'type' => 'export',
  'transport' => 'sea',
  'buying_coa_id' => 31,
  'selling_coa_id' => 31,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 156,
  'code' => 'RPJT',
  'name' => 'Storage Charge Pjt',
  'full_name' => 'RPJT, Storage Charge Pjt [WRHS]',
  'type' => '',
  'transport' => '',
  'buying_coa_id' => 153,
  'selling_coa_id' => 85,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 157,
  'code' => 'RRWR',
  'name' => 'Sea Repair And Wash Reimb',
  'full_name' => 'RRWR, Sea Repair And Wash Reimb [RMBS]',
  'type' => '',
  'transport' => 'sea',
  'buying_coa_id' => 31,
  'selling_coa_id' => 31,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 158,
  'code' => 'RSTO',
  'name' => 'Sea Storage Reimb',
  'full_name' => 'RSTO, Sea Storage Reimb [RMBS]',
  'type' => '',
  'transport' => 'sea',
  'buying_coa_id' => 31,
  'selling_coa_id' => 31,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 159,
  'code' => 'RSTR',
  'name' => 'Sea Lcl Stripping Reimb',
  'full_name' => 'RSTR, Sea Lcl Stripping Reimb [RMBS]',
  'type' => '',
  'transport' => 'sea',
  'buying_coa_id' => 31,
  'selling_coa_id' => 31,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 160,
  'code' => 'RTHC',
  'name' => 'Sea Thc Reimb',
  'full_name' => 'RTHC, Sea Thc Reimb [RMBS]',
  'type' => '',
  'transport' => 'sea',
  'buying_coa_id' => 31,
  'selling_coa_id' => 31,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 161,
  'code' => 'RTPS',
  'name' => 'Storage Charge Pib',
  'full_name' => 'RTPS, Storage Charge Pib [WRHS]',
  'type' => '',
  'transport' => '',
  'buying_coa_id' => 151,
  'selling_coa_id' => 83,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 162,
  'code' => 'RTRM',
  'name' => 'Sea Trucking Reimb',
  'full_name' => 'RTRM, Sea Trucking Reimb [RMBS]',
  'type' => '',
  'transport' => 'sea',
  'buying_coa_id' => 31,
  'selling_coa_id' => 31,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 163,
  'code' => 'RUBM',
  'name' => 'Sea Loading Unloading Reimb',
  'full_name' => 'RUBM, Sea Loading Unloading Reimb [RMBS]',
  'type' => '',
  'transport' => 'sea',
  'buying_coa_id' => 31,
  'selling_coa_id' => 31,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 164,
  'code' => 'SELO',
  'name' => 'Sea Export Lift On Reimb',
  'full_name' => 'SELO, Sea Export Lift On Reimb [RMBS]',
  'type' => 'export',
  'transport' => 'sea',
  'buying_coa_id' => 31,
  'selling_coa_id' => 31,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 165,
  'code' => 'SELU',
  'name' => 'Sea Export Loading Unloading Reimb',
  'full_name' => 'SELU, Sea Export Loading Unloading Reimb [RMBS]',
  'type' => 'export',
  'transport' => 'sea',
  'buying_coa_id' => 31,
  'selling_coa_id' => 31,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 166,
  'code' => 'SEMP',
  'name' => 'Export Sea Meterai',
  'full_name' => 'SEMP, Export Sea Meterai [STMP]',
  'type' => 'export',
  'transport' => 'sea',
  'buying_coa_id' => 250,
  'selling_coa_id' => 250,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 167,
  'code' => 'SETO',
  'name' => 'Sea Export Storage Reimb',
  'full_name' => 'SETO, Sea Export Storage Reimb [RMBS]',
  'type' => 'export',
  'transport' => 'sea',
  'buying_coa_id' => 31,
  'selling_coa_id' => 31,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 168,
  'code' => 'SEUN',
  'name' => 'Sea Export Licence Fee',
  'full_name' => 'SEUN, Sea Export Licence Fee [HDLG]',
  'type' => 'export',
  'transport' => 'sea',
  'buying_coa_id' => 31,
  'selling_coa_id' => 31,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 169,
  'code' => 'SFFZ',
  'name' => 'Import Sea Freight Fcl 40',
  'full_name' => 'SFFZ, Import Sea Freight Fcl 40 [FRGT]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 177,
  'selling_coa_id' => 109,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 170,
  'code' => 'SFRF',
  'name' => 'Import Sea Freight Fcl 45',
  'full_name' => 'SFRF, Import Sea Freight Fcl 45 [FRGT]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 177,
  'selling_coa_id' => 109,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 171,
  'code' => 'SFRT',
  'name' => 'Import Sea Freight Fcl 20',
  'full_name' => 'SFRT, Import Sea Freight Fcl 20 [FRGT]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 177,
  'selling_coa_id' => 109,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 172,
  'code' => 'STMP',
  'name' => 'Import Sea Meterai',
  'full_name' => 'STMP, Import Sea Meterai [STMP]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 250,
  'selling_coa_id' => 250,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 173,
  'code' => 'TGCS',
  'name' => 'Import Sea Terminal Gate Charges',
  'full_name' => 'TGCS, Import Sea Terminal Gate Charges [FRGT]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 177,
  'selling_coa_id' => 109,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 174,
  'code' => 'TLCL',
  'name' => 'Import Sea Trucking  Local Lcl',
  'full_name' => 'TLCL, Import Sea Trucking  Local Lcl [TRCK]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 191,
  'selling_coa_id' => 123,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 175,
  'code' => 'TLF2',
  'name' => 'Import Sea Trucking  Local Fcl 20',
  'full_name' => 'TLF2, Import Sea Trucking  Local Fcl 20 [TRCK]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 188,
  'selling_coa_id' => 120,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 176,
  'code' => 'TLF4',
  'name' => 'Import Sea Trucking  Local Fcl 40',
  'full_name' => 'TLF4, Import Sea Trucking  Local Fcl 40 [TRCK]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 189,
  'selling_coa_id' => 121,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 177,
  'code' => 'TLF5',
  'name' => 'Import Sea Trucking  Local Fcl 45',
  'full_name' => 'TLF5, Import Sea Trucking  Local Fcl 45 [TRCK]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 190,
  'selling_coa_id' => 122,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 178,
  'code' => 'TLXX',
  'name' => 'Import Sea Telex Fee',
  'full_name' => 'TLXX, Import Sea Telex Fee [FRGT]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 177,
  'selling_coa_id' => 109,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 179,
  'code' => 'TPCA',
  'name' => 'Import Air Transhipment Charges',
  'full_name' => 'TPCA, Import Air Transhipment Charges [FRGT]',
  'type' => 'import',
  'transport' => 'air',
  'buying_coa_id' => 176,
  'selling_coa_id' => 108,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 180,
  'code' => 'TPCS',
  'name' => 'Import Sea Transhipment Charges',
  'full_name' => 'TPCS, Import Sea Transhipment Charges [FRGT]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 177,
  'selling_coa_id' => 109,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 181,
  'code' => 'TRKF',
  'name' => 'Import Air Trucking Fee (Agent]',
  'full_name' => 'TRKF, Import Air Trucking Fee (Agent] [FRGT]',
  'type' => 'import',
  'transport' => 'air',
  'buying_coa_id' => 176,
  'selling_coa_id' => 108,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 182,
  'code' => 'TS20',
  'name' => 'Import Sea Trucking Fcl 20',
  'full_name' => 'TS20, Import Sea Trucking Fcl 20 [TRCK]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 188,
  'selling_coa_id' => 120,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 183,
  'code' => 'TS40',
  'name' => 'Import Sea Trucking Fcl 40',
  'full_name' => 'TS40, Import Sea Trucking Fcl 40 [TRCK]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 189,
  'selling_coa_id' => 121,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 184,
  'code' => 'TS45',
  'name' => 'Import Sea Trucking Fcl 45',
  'full_name' => 'TS45, Import Sea Trucking Fcl 45 [TRCK]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 190,
  'selling_coa_id' => 122,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 185,
  'code' => 'VGMS',
  'name' => 'Import Sea Vgm',
  'full_name' => 'VGMS, Import Sea Vgm [FRGT]',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 177,
  'selling_coa_id' => 109,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 186,
  'code' => 'WHCL',
  'name' => 'Contract Logistic',
  'full_name' => 'WHCL, Contract Logistic [WRHS]',
  'type' => '',
  'transport' => '',
  'buying_coa_id' => 204,
  'selling_coa_id' => 136,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 187,
  'code' => 'WHFM',
  'name' => 'Fullfillment',
  'full_name' => 'WHFM, Fullfillment [WRHS]',
  'type' => '',
  'transport' => '',
  'buying_coa_id' => 202,
  'selling_coa_id' => 134,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 188,
  'code' => 'WHRL',
  'name' => 'Rental Logistic',
  'full_name' => 'WHRL, Rental Logistic [HDLG]',
  'type' => '',
  'transport' => '',
  'buying_coa_id' => 203,
  'selling_coa_id' => 135,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 189,
  'code' => 'WHTL',
  'name' => 'Trucking Logistic',
  'full_name' => 'WHTL, Trucking Logistic [WRHS]',
  'type' => '',
  'transport' => '',
  'buying_coa_id' => 205,
  'selling_coa_id' => 137,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 190,
  'code' => 'WSRL',
  'name' => 'Rental Logistic',
  'full_name' => 'WSRL, Rental Logistic [WRHS]',
  'type' => '',
  'transport' => '',
  'buying_coa_id' => 203,
  'selling_coa_id' => 135,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:43:54',
  'updated_at' => '2025-12-03 09:56:17',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 191,
  'code' => 'TMP-IMPORT-001',
  'name' => 'Tmp Service 1',
  'full_name' => 'TMP-IMPORT-001, Tmp Service 1',
  'type' => 'import',
  'transport' => 'sea',
  'buying_coa_id' => 0,
  'selling_coa_id' => 0,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:45:48',
  'updated_at' => '2025-12-03 09:46:08',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 192,
  'code' => 'TMP-IMPORT-002',
  'name' => 'Tmp Service 2',
  'full_name' => 'TMP-IMPORT-002, Tmp Service 2',
  'type' => 'export',
  'transport' => 'air',
  'buying_coa_id' => 0,
  'selling_coa_id' => 0,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:45:48',
  'updated_at' => '2025-12-03 09:46:08',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 193,
  'code' => 'SRGN',
  'name' => 'SERVICE GENSET / INV:188 / GANTI OLI,FILTER OLI,DLL',
  'full_name' => 'SRGN, SERVICE GENSET / INV:188 / GANTI OLI,FILTER OLI,DLL [OTPY]',
  'type' => '',
  'transport' => '',
  'buying_coa_id' => 245,
  'selling_coa_id' => 245,
  'is_active' => 1,
  'created_at' => '2025-12-03 09:58:00',
  'updated_at' => '2025-12-03 09:58:00',
  'service_charge_group_id' => NULL,
  'item_type_id' => NULL,
],
            [
  'id' => 194,
  'code' => 'PCLS',
  'name' => 'PENSIL TULIS INUL',
  'full_name' => 'PCLS, PENSIL TULIS INUL [CSTM]',
  'type' => '',
  'transport' => '',
  'buying_coa_id' => 45,
  'selling_coa_id' => 45,
  'is_active' => 1,
  'created_at' => '2025-12-05 09:51:37',
  'updated_at' => '2025-12-05 09:55:54',
  'service_charge_group_id' => 4,
  'item_type_id' => NULL,
],
            [
  'id' => 195,
  'code' => 'TBLS',
  'name' => 'Meja Tamu',
  'full_name' => 'TBLS, Meja Tamu [CSTM]',
  'type' => NULL,
  'transport' => 'air',
  'buying_coa_id' => 45,
  'selling_coa_id' => 45,
  'is_active' => 1,
  'created_at' => '2025-12-08 08:45:45',
  'updated_at' => '2025-12-09 01:17:34',
  'service_charge_group_id' => 4,
  'item_type_id' => 1,
],
            [
  'id' => 196,
  'code' => 'TLUR',
  'name' => 'TELUR OMEGA 3 PREMIUM',
  'full_name' => 'TLUR, TELUR OMEGA 3 PREMIUM [OTPY]',
  'type' => NULL,
  'transport' => 'air',
  'buying_coa_id' => 218,
  'selling_coa_id' => 218,
  'is_active' => 1,
  'created_at' => '2025-12-09 02:12:49',
  'updated_at' => '2025-12-09 02:12:49',
  'service_charge_group_id' => NULL,
  'item_type_id' => 4,
],
            [
  'id' => 197,
  'code' => 'RTPT',
  'name' => 'ROTI BANTAL GANDUM',
  'full_name' => 'RTPT, ROTI BANTAL GANDUM [FOOD]',
  'type' => NULL,
  'transport' => 'air',
  'buying_coa_id' => 218,
  'selling_coa_id' => 218,
  'is_active' => 1,
  'created_at' => '2025-12-09 02:14:02',
  'updated_at' => '2025-12-09 03:33:38',
  'service_charge_group_id' => 4,
  'item_type_id' => 5,
],
            [
  'id' => 198,
  'code' => 'RTCK',
  'name' => 'ROTI COKLAT',
  'full_name' => 'RTCK, ROTI COKLAT [FOOD]',
  'type' => NULL,
  'transport' => 'air',
  'buying_coa_id' => 218,
  'selling_coa_id' => 218,
  'is_active' => 1,
  'created_at' => '2025-12-09 03:34:20',
  'updated_at' => '2025-12-09 03:34:20',
  'service_charge_group_id' => 4,
  'item_type_id' => 5,
]
        ]);
        
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
